# Thanks for downloading mCoins plugin!
# You rock bro - Veltus

debug-messages: true

manage-permission: coins.admin
mysql:
  host: localhost
  port: 3306
  database: coins
  username: admin
  password: 5184