#
#  mCoins
#
#  Thanks for Downloading mCoins!
#  You rock bro! - Veltus & GrowlyX
#
debug-messages: true
manage-permission: coins.admin
mysql:
  host: localhost
  port: 3306
  database: coins
  username: admin
  password: 'password'