# Thanks for downloading my plugin!
# You rock bro - Veltus

debug-messages: true
mysql:
  host: '170.10.163.64'
  port: 3306
  database: descentv_coins
  username: descentv_admin
  password: sexdicks123
