name: Coins
version: 1.4
main: vip.descent.coins.CoinsHandler
author: veltus5184
description: Lightweight Coins Plugin
commands:
  coins:
    description: Coins command!
    aliases: [money, cash]
